-- return {
-- 	"rcarriga/nvim-notify",
-- 	config = function()
-- 		require("notify").setup({
-- 			stages = "fade",
-- 			timeout = 5000,
-- 			background_colour = "#000000",
-- 		})
-- 	end,
-- }
return {}
